<?php
add_filter('geodir_custom_field_output_address','chm_short_state_geodir_cf_address',11,3);

function chm_short_state_geodir_cf_address($html,$location,$cf){
	// we add the >NAME< so we only replace the regions and not the region name in a street address.
	$state_long = array(
		'addressRegion">Alabama<',
		'addressRegion">Alaska<',
		'addressRegion">Philadelphia<',
	    'addressRegion">Arizona<',
		'addressRegion">Arkansas<',
		'addressRegion">California<',
		'addressRegion">Colorado<',
		'addressRegion">Connecticut<',
		'addressRegion">Delaware<',
		'addressRegion">District of Columbia<',
		'addressRegion">Florida<',
		'addressRegion">Georgia<',
		'addressRegion">Hawaii<',
		'addressRegion">Idaho<',
		'addressRegion">Illinois<',
		'addressRegion">Indiana<',
	    'addressRegion">Iowa<',
		'addressRegion">Kansas<',
		'addressRegion">Kentucky<',
		'addressRegion">Louisiana<',
		'addressRegion">Maine<',
		'addressRegion">Maryland<',
		'addressRegion">Massachusetts<',
		'addressRegion">Michigan<',
		'addressRegion">Mississippi<',
		'addressRegion">Missouri<',
		'addressRegion">Montana<',
		'addressRegion">Nebraska<',
		'addressRegion">Nevada<',
		'addressRegion">New Hampshire<',
		'addressRegion">New Jersey<',
		'addressRegion">New Mexico<',
		'addressRegion">New York<',
		'addressRegion">North Carolina<',
		'addressRegion">North Dakota<',
		'addressRegion">Ohio<',
		'addressRegion">Oklahoma<',
		'addressRegion">Oregon<',
		'addressRegion">Pennsylvania<',
		'addressRegion">Rhode Island<',
		'addressRegion">South Carolina<',
	  	'addressRegion">Tennessee<',
	  	'addressRegion">Texas<',
	  	'addressRegion">Utah<',
	  	'addressRegion">Vermont<',
	  	'addressRegion">Virginia<',
	  	'addressRegion">Washington<',
	  	'addressRegion">West Virginia<',
	  	'addressRegion">Wisconsin<',
	  	'addressRegion">Wyoming<',
	);
	// we add the >NAME< so we only replace the regions and not the region name in a street address.
	$state_short = array(
		'addressRegion">AL<',
		'addressRegion">AK<',
		'addressRegion">pd<',
		'addressRegion">AZ<',
		'addressRegion">AR<',
		'addressRegion">CA<',
		'addressRegion">CO<',
		'addressRegion">CT<',
		'addressRegion">DE<',
		'addressRegion">DC<',
		'addressRegion">FL<',
		'addressRegion">GA<',
		'addressRegion">HI<',
		'addressRegion">ID<',
		'addressRegion">IL<',
		'addressRegion">IN<',
		'addressRegion">IA<',
		'addressRegion">KS<',
		'addressRegion">KY<',
		'addressRegion">LA<',
		'addressRegion">MN<',
		'addressRegion">MD<',
		'addressRegion">MA<',
	    'addressRegion">MI<',
		'addressRegion">MS<',
		'addressRegion">MO<',
		'addressRegion">MT<',
		'addressRegion">NE<',
		'addressRegion">NV<',
		'addressRegion">NH<',
		'addressRegion">NJ<',
		'addressRegion">NM<',
		'addressRegion">NY<',
		'addressRegion">NC<',
		'addressRegion">ND<',
		'addressRegion">OH<',
		'addressRegion">OK<',
		'addressRegion">OR<',
		'addressRegion">PA<',
		'addressRegion">RI<',
		'addressRegion">SC<',
		'addressRegion">TN<',
		'addressRegion">TX<',
		'addressRegion">UT<',
		'addressRegion">VT<',
		'addressRegion">VA<',
		'addressRegion">WA<',
		'addressRegion">WV<',
		'addressRegion">WI<',
		'addressRegion">WY<',
	);

	$html = str_replace($state_long,$state_short,$html);

	return $html;
}
